social_counters.social_counters_config.*:
  type: mapping
  label: 'Social Counters Config'
  mapping:
    id:
      type: string
      label: 'Social Counters Config id'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Name'
    plugin_id:
      type: string
      label: 'Plugin id'
    config:
      type: string
      label: 'Configuration'