button_option: stbc_vcount
comments: 0
late_load: 0
location: content
node_types:
  blog: blog
  article: null
  gallery: null
  news: null
  page: null
option_extras:
  'Google Plus One:plusone': 'Google Plus One:plusone'
  'Facebook Like:fblike': 'Facebook Like:fblike'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''Vkontakte:vkontakte'',''Twitter:twitter'',''Facebook:facebook'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 25
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  blog:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  gallery:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  news:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-2a9c8a90-4497-be9a-9322-15c3bca94d4b
callesi: '0'
